### ISSUE TITLE
Failed to resolve: com.nbsp:library:1.2

### ISSUE THREAD

**Issue by sakshi678** [RajneeshSingh007/College-Management--Android-App#1]
Error:(73, 13) Failed to resolve: com.nbsp:library:1.2
<a href="openFile:C:/Users/Sakshi/Desktop/College-Management--Android-App-master/College-Management--Android-App-master/Slrtce/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a> 

whats wrong here?
and where I am wrong? 
What should I do now?

**Comment by RajneeshSingh007** [comment]
Kindly,
Add
maven {
        url "http://dl.bintray.com/lukaville/maven"
    }
in the build.gradle(Project)

Best Regards,
Rajneesh Singh
