### ISSUE TITLE
Stuck on registration. 

### ISSUE THREAD

**Issue by V4nill4** [RajneeshSingh007/College-Management--Android-App#5]
After doing everything in the Readme, sign up gets stuck on registration. Is there any specific version of wamp server that I'm supposed to use?

**Comment by RajneeshSingh007** [comment]
Hello,
It's issue of network connectivity,
Please,check url in postman (software for website debugging) or in browser.
Also,share logs.

**Comment by V4nill4** [comment]
Thanks for your reply. Made it work after trying a few times. It was a database url issue. Fixed now.

**Comment by aditya798** [comment]
i am facing same problem plz help me

**Comment by RajneeshSingh007** [comment]
@aditya798 Please, check url is correct or not,
Also, there is email verification setup so launch paper cut (email testing tool on local) else configure server for email.
You can disable email verification in register, login php files and set active value  to 1 in table of student, teacher, notteacher.

**Comment by aditya798** [comment]
hello rajneesh thanks for ur reply i tried but can't find the error if u
have any free time plz help me through team viewer
7408621866 is my contact no plz help me if possible for u
thank you
